# Generated by Django 3.2.25 on 2024-08-26 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20240826_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
    ]
