# Generated by Django 3.2.25 on 2024-08-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_groupmessage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_groups',
            field=models.ManyToManyField(blank=True, related_name='blocked_users', to='base.ChatGroup'),
        ),
    ]
