# Generated by Django 5.1.1 on 2024-09-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_user_blocked_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
