# Generated by Django 5.1.1 on 2024-09-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_room_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='matches',
            field=models.JSONField(default=dict),
        ),
    ]
