# Generated by Django 5.1.1 on 2024-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_room_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='matches',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
