# Generated by Django 4.2.16 on 2024-11-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_remove_room_participants_shuffled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='final_player1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='final_player2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
