# Generated by Django 4.2.16 on 2024-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_room_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_semiset',
            field=models.BooleanField(default=False),
        ),
    ]
