# Generated by Django 4.2.16 on 2024-11-16 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_room_is_semiset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_semiset',
            new_name='is_completed',
        ),
    ]
