# Generated by Django 4.2.16 on 2024-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_user_losses_user_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
